version: "3"
services:
  jupyterlab:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    container_name: jupyterlab
    env_file:
      - .env
    user: root
